# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_cDsnLsYxpW2B44-GZv1WojspbacxFI

Numpy Array Operations:
"""

import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:", temperatures_w1)

import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:", temperatures_w1)

print("Shape of temperatures_w1:", temperatures_w1.shape)
print("Data type of temperatures_w1:", temperatures_w1.dtype)
print("Number of elements in temperatures_w1:", temperatures_w1.size)

temperatures_w1_fahrenheit = (temperatures_w1 * 9/5) + 32
print("Week 1 Temperatures in Fahrenheit:", temperatures_w1_fahrenheit)

max_temp_w1 = np.max(temperatures_w1)
min_temp_w1 = np.min(temperatures_w1)
mean_temp_w1 = np.mean(temperatures_w1)

print(f"Maximum temperature for Week 1: {max_temp_w1}°C")
print(f"Minimum temperature for Week 1: {min_temp_w1}°C")
print(f"Mean temperature for Week 1: {mean_temp_w1:.2f}°C")

# 1. Temperatures for the first three days
temp_first_three_days = temperatures_w1[:3]
print("Temperatures for the first three days:", temp_first_three_days)

# 2. Temperatures for the weekend (last two days)
temp_weekend = temperatures_w1[-2:]
print("Temperatures for the weekend:", temp_weekend)

# 3. Temperatures for the middle three days
temp_middle_three_days = temperatures_w1[2:5] # Indices 2, 3, 4 for middle three
print("Temperatures for the middle three days:", temp_middle_three_days)

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])
print("2D Temperature Array:\n", temperatures)

print("Shape of temperatures array:", temperatures.shape)
print("Data type of temperatures array:", temperatures.dtype)
print("Number of elements in temperatures array:", temperatures.size)

temperatures_week1 = temperatures[0]
temperatures_week2 = temperatures[1]

print("Temperatures for Week 1:", temperatures_week1)
print("Temperatures for Week 2:", temperatures_week2)

weekend_temperatures_week1 = temperatures[0, -2:]
weekend_temperatures_week2 = temperatures[1, -2:]

print("Weekend temperatures for Week 1:", weekend_temperatures_week1)
print("Weekend temperatures for Week 2:", weekend_temperatures_week2)

"""Pandas Series"""

import pandas as pd

marks_data = [95, 92, 89, 85, 80]
marks_indices = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']

marks = pd.Series(marks_data, index=marks_indices)

print("Pandas Series 'marks':\n", marks)

mark_rank1_int_index = marks.iloc[0]
print("Mark of the 1st rank student (using integer index):", mark_rank1_int_index)

marks_top3_loc = marks.loc[['Rank1', 'Rank2', 'Rank3']]
print("Marks of the top 3 ranks (using loc):\n", marks_top3_loc)

mark_rank3_iloc = marks.iloc[2]
print("Mark of the 3rd rank student (using iloc):", mark_rank3_iloc)

marks_greater_than_90 = marks[marks > 90]
print("Ranks with marks greater than 90:\n", marks_greater_than_90)

marks.loc['Rank1'] = 100
print("Marks Series after updating Rank1:\n", marks)

marks_after_drop = marks.drop('Rank5')
print("Marks Series after removing Rank5:\n", marks_after_drop)

cgpa = marks / 10
print("CGPA for each rank:\n", cgpa)

"""Pandas DataFrame:"""

import pandas as pd

transactions_data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(transactions_data)

display(transactions.head())

display(transactions)

print("\nHead of the DataFrame:")
display(transactions.head())

print("\nTail of the DataFrame:")
display(transactions.tail())

print("\nShape of the DataFrame (rows, columns):")
print(transactions.shape)

print("\nColumn names:")
print(transactions.columns.tolist())

print("\nData types:")
print(transactions.dtypes)

product_category_amount = transactions[['ProductCategory', 'Amount']]
print("DataFrame with 'ProductCategory' and 'Amount' columns:")
display(product_category_amount)

last_3_columns = transactions.iloc[:, -3:]
print("Last 3 columns of the DataFrame:")
display(last_3_columns)

filtered_transactions = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print("Transactions in 'North' region with 'Amount' greater than 200:")
display(filtered_transactions)

product_category_counts = transactions['ProductCategory'].value_counts()
print("Value counts for 'ProductCategory':")
display(product_category_counts)

unique_regions = transactions['Region'].unique()
print("Unique values in 'Region':")
print(unique_regions)

mean_amount_by_region = transactions.groupby('Region')['Amount'].mean().reset_index()
print("Mean amount for each region:")
display(mean_amount_by_region)

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("DataFrame after modifying 'Amount' for TransactionID 102:")
display(transactions)

transactions['Discount'] = transactions['Amount'] * 0.10
print("DataFrame after adding 'Discount' column:")
display(transactions)

transactions = transactions[transactions['TransactionID'] != 109]
print("DataFrame after removing the row with TransactionID 109:")
display(transactions)

transactions = transactions.drop(columns=['Discount'])
print("DataFrame after deleting the 'Discount' column:")
display(transactions)