# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_guQuRv6AG9YFFxfXcL4WI6sVdZA4XoB
"""

import random

secret_number = random.randint(1, 10)
print("Welcome to the Number Guessing Game!")
print("I have picked a number between 1 and 10. You have 3 attempts to guess it.")

attempts = 3

while attempts > 0:
    try:
        user_guess = int(input(f"Enter your guess (Attempts left: {attempts}): "))

        if 1 <= user_guess <= 10:
            pass
        else:
            print("Your guess is out of the 1-10 range. Please try again.")
            continue

        if user_guess < secret_number:
            print("Too low! Try again.")
        elif user_guess > secret_number:
            print("Too high! Try again.")
        else:
            print(f"Congratulations! You guessed the number {secret_number} correctly!")
            break # Exit the loop if the guess is correct

        attempts -= 1

    except ValueError:
        print("Invalid input. Please enter an integer.")
        continue
else:
    # This 'else' block executes if the 'while' loop finishes without a 'break'
    # which means attempts ran out without a correct guess.
    print(f"Better luck next time! The number was {secret_number}.")

while True:
    try:
        user_number = int(input("Enter a number to generate its multiplication table: "))
        break
    except ValueError:
        print("Invalid input. Please enter an integer.")

print(f"\nMultiplication Table for {user_number}:")

for i in range(1, 11):
    result = user_number * i
    print(f"{user_number} x {i} = {result}")

def calculate_bmi(weight_kg, height_m):

    if height_m <= 0:
        raise ValueError("Height must be a positive number.")
    bmi = weight_kg / (height_m ** 2)
    return bmi

while True:
    try:
        weight_str = input("Enter your weight in kilograms (kg): ")
        weight = float(weight_str)
        if weight <= 0:
            print("Weight must be a positive number. Please try again.")
        else:
            break
    except ValueError:
        print("Invalid input for weight. Please enter a numerical value.")


while True:
    try:
        height_str = input("Enter your height in meters (m): ")
        height = float(height_str)
        if height <= 0:
            print("Height must be a positive number. Please try again.")
        else:
            break
    except ValueError:
        print("Invalid input for height. Please enter a numerical value.")


try:
    bmi_value = calculate_bmi(weight, height)
    print(f"\nYour Body Mass Index (BMI) is: {bmi_value:.2f}")
except ValueError as e:
    print(f"Error: {e}")

