# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uu8R28oHh8fJlnZv3WFji8NgGn11VFXD
"""

feedback_data = {
'S_No': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
'Name': ['Ravi', 'Meera', 'Sam', 'Anu', 'Raj', 'Divya', 'Arjun', 'Kiran', 'Leela', 'Nisha'],
'Feedback': [
' Very GOOD Service!!!',
'poor support, not happy ',
'GREAT experience! will come again.',
'okay okay...',
' not BAD',
'Excellent care, excellent staff!',
'good food and good ambience!',
'Poor response and poor handling of issue',
'Satisfied. But could be better.',
'Good support... quick service.'
],
'Rating': [5, 2, 5, 3, 2, 5, 4, 1, 3, 4]
}

num_feedbacks = int(input("How many more feedbacks would you like to add? "))

current_s_no = len(feedback_data['S_No']) + 1

for i in range(num_feedbacks):
    print(f"\nEntering feedback #{i+1} (S_No: {current_s_no}):")
    name = input("Enter Name: ")
    feedback_text = input("Enter Written Feedback: ")

    while True:
        try:
            rating = int(input("Enter Rating (1-5): "))
            if 1 <= rating <= 5:
                break
            else:
                print("Rating must be between 1 and 5. Please try again.")
        except ValueError:
            print("Invalid input. Please enter a number for the rating.")

    feedback_data['S_No'].append(current_s_no)
    feedback_data['Name'].append(name)
    feedback_data['Feedback'].append(feedback_text)
    feedback_data['Rating'].append(rating)

    current_s_no += 1

print("\nNew feedback added successfully!")

def clean_feedback(feedback_text):

    cleaned_text = feedback_text.lower()

    cleaned_text = re.sub(r'[.,!?-]', '', cleaned_text)

    cleaned_text = ' '.join(cleaned_text.split())
    return cleaned_text


cleaned_feedbacks = [clean_feedback(feedback) for feedback in feedback_data['Feedback']]
feedback_data['Feedback'] = cleaned_feedbacks

print("Feedback entries cleaned successfully!")

def count_word_in_feedbacks(word):
    count = 0
    search_word = word.lower()
    for feedback in feedback_data['Feedback']:
        if search_word in feedback:
            count += 1
    return count

good_count = count_word_in_feedbacks("good")
print(f"Number of feedbacks containing 'good': {good_count}")

poor_count = count_word_in_feedbacks("poor")
print(f"Number of feedbacks containing 'poor': {poor_count}")

excellent_count = count_word_in_feedbacks("excellent")
print(f"Number of feedbacks containing 'excellent': {excellent_count}")

"""### Final Cleaned Feedback Data"""

print("Final Cleaned feedback_data:")

"""### Average Rating"""

average_rating = sum(feedback_data['Rating']) / len(feedback_data['Rating'])
print(f"Average Rating from all feedbacks: {average_rating:.2f}")

"""### Feedback with Longest Comment (Word Count)"""

longest_feedback_text = ""
max_word_count = 0
longest_feedback_index = -1

for i, feedback_text in enumerate(feedback_data['Feedback']):
    word_count = len(feedback_text.split())
    if word_count > max_word_count:
        max_word_count = word_count
        longest_feedback_text = feedback_text
        longest_feedback_index = i

if longest_feedback_index != -1:
    print(f"Feedback with the longest comment (Word Count: {max_word_count}):")
    print(f"  S_No: {feedback_data['S_No'][longest_feedback_index]}")
    print(f"  Name: {feedback_data['Name'][longest_feedback_index]}")
    print(f"  Feedback: '{longest_feedback_text}'")
    print(f"  Rating: {feedback_data['Rating'][longest_feedback_index]}")
else:
    print("No feedback comments found.")

"""### Unique Words Across All Feedbacks"""

unique_words = set()
for feedback_text in feedback_data['Feedback']:
    for word in feedback_text.split():
        unique_words.add(word)

print("Unique words used across all feedbacks:")
print(sorted(list(unique_words)))

"""### Feedbacks Sorted by Rating (Highest to Lowest)"""

combined_feedback = list(zip(
    feedback_data['S_No'],
    feedback_data['Name'],
    feedback_data['Feedback'],
    feedback_data['Rating']
))

sorted_feedback = sorted(combined_feedback, key=lambda x: x[3], reverse=True)

print("Feedbacks sorted by Rating (Highest to Lowest):")
print("S_No | Name      | Feedback                           | Rating")
print("--------------------------------------------------------------")
for s_no, name, feedback, rating in sorted_feedback:
    print(f"{s_no:<4} | {name:<9} | {feedback:<34} | {rating}")

