# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tgG8dqPK9JVMya5VxX-yLU230lMGI3Kc
"""

string1 = "Hello "
string2 = input("Enter your name: ")

concatenated_string = string1 + string2

print(concatenated_string)

string3 = ", welcome to Python programming"

concatenated_string_final = concatenated_string + string3

print(concatenated_string_final)

input_string = concatenated_string_final

# a. Print the first character of the string.
print(f"First character: {input_string[0]}")

# b. Print the last character of the string.
print(f"Last character: {input_string[-1]}")

# c. Print the first 5 characters of the string.
print(f"First 5 characters: {input_string[0:5]}")

# d. Print the last 11 characters of the string.
print(f"Last 11 characters: {input_string[-11:]}")

# e. Print the string in reverse.
print(f"String in reverse: {input_string[::-1]}")

# f. Use slicing and print the word “Python” from the existing string.
python_start_index = input_string.find("Python")
if python_start_index != -1:
    print(f"Word 'Python': {input_string[python_start_index : python_start_index + len('Python')]}")
else:
    print("Word 'Python' not found in the string.")

strM = "Python beginner tutorial"

# a. Convert the sentence to uppercase.
uppercase_strM = strM.upper()
print(f"Uppercase: {uppercase_strM}")

# b. Convert the sentence to lowercase.
lowercase_strM = strM.lower()
print(f"Lowercase: {lowercase_strM}")

# c. Use Capitalize and return the sentence to the original input form.
capitalized_strM = strM.capitalize()
print(f"Capitalized (first letter uppercase, rest lowercase): {capitalized_strM}")
print(f"Original form: {strM}")

# d. Count the total number of occurrences of character ‘t’ in the string.
count_t = strM.count('t')
print(f"Occurrences of 't': {count_t}")

# e. Replace all occurrences of “Python” with “Machine Learning” in the input string
replaced_strM = strM.replace("Python", "Machine Learning")
print(f"String after replacement: {replaced_strM}")

tuple1 = (10, 20, 30)
tuple2 = (40, 50, 60)

# a. Concatenate the two tuples and store it in “t_combine”
t_combine = tuple1 + tuple2
print({t_combine})

# b. Repeat the elements of “t_combine” 3 times
t_repeated = t_combine * 3
print(f"Repeated t_combine (3 times): {t_repeated}")

# c. Access the 3rd element from “t_combine” (index 2)
third_element = t_combine[2]
print(f"3rd element of t_combine: {third_element}")

# d. Access the first three elements from “t_combine”
first_three_elements = t_combine[0:3]
print(f"First three elements of t_combine: {first_three_elements}")

# e. Access the last three elements from “t_combine”
last_three_elements = t_combine[-3:]
print(f"Last three elements of t_combine: {last_three_elements}")

a=int(input("enter a number"))
b=int(input("enter a number"))
c=a+b
print(c)

a=int(input("enter a number"))
b=int(input("enter a number"))
c=a+b
print(c)

a=int(input("enter first number"))
b=int(input("enter second number"))
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

z=10
z+=5
print(z)

z-=10
print(z)

z*=2
print(z)

a = int(input("enter first number"))
b = int(input("enter second number"))
print(a == b)
print(a != b)

print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

age = int(input('enter a number'))
print(age >= 18 and age <= 60)

a = 10
b = 20
print(a > 15 or b < 15)

if 10>5:
 print("10 is greater")

a=int(input("enter a number"))
b=int(input("enter a number"))
if a>b:
 print("a is greater")

a=int(input("enter a number"))
if a>0:
  print("a is positive")
else:
  print("a is negative")

a= int(input("Enter a positive number"))
if(a>0):
  print("positive")
else :
  print("negative")

a=int(input("enter a number"))
if a%2==0:
   print("a is even")
else:
   print("odd")

a=int(input("enter a number"))
b=int(input("enter a number"))
if a>b:
  print("a is greater")
elif a<b:
  print("b is greater")
else:
  print("both are equal")

a=int(input("enter a number"))
if a>0:
  print("a is positive")
else:
  print("a is negative")

a = int(input("enter a number"))

if a > 0:
    print("a is positive")
elif a == 0:
    print("a is zero")
else:
    print("a is negative")

a=input("password:")
if a=="hello":
  print("password is correct")
else:
  print("password is incorrect")

a=input("password:")
if a=="hello":
  print("password is correct")
else:
  print("password is incorrect")

t=(1,2,7,4,5)
b=list(t)
b[2]=3
print(b)
t=tuple(b)
print(t)