# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uea4pSoSmDeTx4kBR6SFZVBr51G4cRDs
"""

age_list = [24, 25, 26, 27, 28]
print(age_list)

name_list = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
print(name_list)

name_list.append('Yazhini')
print(name_list)

age_list.insert(2, 30)
print(age_list)

name_list.remove('Yazhini')
print(name_list)

age_list.pop()
print(age_list)

age_list.extend([29, 30, 26])
print(age_list)

age_list.sort(reverse=True)
print(age_list)

max_age = max(age_list)
min_age = min(age_list)
sum_ages = sum(age_list)

print(f"Maximum age: {max_age}")
print(f"Minimum age: {min_age}")
print(f"Sum of all ages: {sum_ages}")

print(name_list[0])

print(name_list[-1])

print(name_list[2:5])

name_list.sort(reverse=True)
print(name_list)

student_marks = {
    'Alice': 85,
    'Bob': 92,
    'Charlie': 78,
    'David': 65,
    'Eve': 95
}
print(student_marks)

print(f"Alice's mark: {student_marks['Alice']}")

student_marks['Janani'] = 80
print(student_marks)

student_marks['Alice'] = 82
print(student_marks)

print("Keys:", student_marks.keys())

print("Values:", student_marks.values())

print("Key-Value Pairs:", student_marks.items())

my_list = ['a','e','i','o','u','a','a','i']
my_set = set(my_list)
print(my_set)

"""Sets only store unique elements. So, when creating my_set from the list ['a','e','i','o','u','a','a','i'], the duplicate 'a' and 'i' values were automatically removed, resulting in the set {'i', 'a', 'e', 'u', 'o'}. The order of elements in a set is not guaranteed.

"""

The `TypeError: 'set' object does not support item assignment` occurs because sets are unordered collections and do not support indexing. You cannot access or modify elements using `my_set[index]`. Instead, you would use methods like `add()` or `remove()` to modify a set.

"""The TypeError: 'set' object does not support item assignment occured because sets are unordered collections and do not support indexing. We cannot access or modify elements using my_set[index]. Instead, We can use methods like add() or remove() to modify a set."""

set1 = {1, 3, 5, 7, 9}
set2 = {2, 3, 5, 8, 10}

print("Set 1:", set1)
print("Set 2:", set2)

union_set = set1.union(set2)
intersection_set = set1.intersection(set2)

print("Union of set1 and set2:", union_set)
print("Intersection of set1 and set2:", intersection_set)

while True:
    try:
        score = int(input("Please enter a score between 0 and 10: "))
        if 0 <= score <= 10:
            print(f"You entered: {score}")
            break
        else:
            print("Invalid input. Please enter a number between 0 and 10.")
    except ValueError:
        print("Invalid input. Please enter an integer.")

if score > 7:
    performance_category = "Above Average"
elif 4 <= score <= 7:
    performance_category = "Average"
else:
    performance_category = "Below Average"

print(f"The score {score} falls into the category: {performance_category}")

print(performance_category)

if performance_category == "Below Average":
    print("Need to Improve your performance, consistent practice will lead to better results")
elif performance_category == "Average":
    print("Good performance, keep up the consistent effort!")
else: # Above Average
    print("Excellent performance, continue to excel!")

